#!/bin/bash

function find_pid() {
    local action="ps -ef | grep '$1' | grep -v grep | awk '{print \$2}'"
    eval $action
}

function kill_pid() {
    for pid in $*
    do
        kill -9 $pid
    done
}

function user_cmd() {
    local action="runuser $1 -s /bin/bash -c '$2'"
    eval $action
}

function get_today() {
    date +%Y-%m-%d
}

function day_ago() {
    date -d "$1 day ago" +%Y-%m-%d
}

function get_timestamp() {
    date -d "$1" +%s
}

function get_mtime() {
    ls --full-time $1 | awk '{print $6}'
}

function get_atime() {
    ls --time atime --full-time $1 | awk '{print $6}'
}

function get_suffix() {
    local suffix=${1##*.}
    if [ $suffix != $1 ]; then
        echo $suffix
    fi
}

function find_at() {
    local mint=$(get_timestamp $2)
    local maxt=$(get_timestamp $3)

    for tail in $(ls $1)
    do
        local p="$1/$tail"
        if [ -f $p ]; then
            local mt=$(get_mtime $p)
            local t=$(get_timestamp $mt)
            if [ $maxt -gt $t -a $mint -lt $t ]; then
                echo "$p"
            fi
        fi
        if [ -d $p ]; then
            find_at $p $2 $3
        fi
    done
}

function add() {
    if [ "$2" == '' ]; then
        echo $(($1 + 1))
    else
        echo $(($1 + $2))
    fi
}
