#!/bin/bash

version=2.26.2
wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-$version.tar.gz
tar xzf git-$version.tar.gz
cd git-$version
./configure --prefix=/usr/local
make && make install