#!/bin/bash
version=3.17.2
wget https://github.com/Kitware/CMake/releases/download/v$version/cmake-$version-Linux-x86_64.tar.gz
tar zxvf cmake-$version-Linux-x86_64.tar.gz
mv cmake-$version-Linux-x86_64 /cmake
ln -sf /cmake/bin/* /usr/bin/
