#!/bin/bash

# 服务端钩子，接收完成后触发。

# 本地拉。
cd /project/path
git pull
chown -R www:www .

# 远程接口，通知远程程序拉代码。
wget --post-data 'user=git&password=PASSWORD&other=info' 'http://your.webhook.com'
curl -d 'user=git&password=PASSWORD&other=info' 'http://your.webhook.com'
